favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "150x"
# logo text will only show when logo is missing.
logo_text = "Earn Money Online"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Ultimate guide to earn money online free. Find legitimate side hustles, passive income ideas, online jobs & more."
author = "Dejuan Jones"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "https://formspree.io/f/xdoreeqg" # contact form works with https://formspree.io
# search
search = true

# Posts related Titles & Contents
categories_title = "Blog Categories"
posts_title = "Featured"
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
featured_post_button = "Featured"
recent_post_button = "Recent"
read_more_button = "Read more"
previous_button = "Previous"
next_button = "Next"
related_posts = "Related Posts"
showing_posts = "Showing Post From"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"

mainSections = ["blog"]
# about widget content
about_widget_content = "Find Us On Social Media."

footer_content = "Empowering you with the best ideas to earn online—because financial freedom starts with the right knowledge."

theme_copyright = true
copyright = "© 2018-2025"

# Google Adsense
adsenseDataAdClient = "ca-pub-9965740454699088"

# 404
error_404_text = "404 Page Not Found!"
error_404_button = "Back To Home"

[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

[banner]
enable = true
title_large = "Earn **Money** Online"
title_small = "Passive Income Ideas"
image = "images/cash-banner.png"
background_image = "/images/banner-bg-shape.svg"
content = "Discover legitimate ways to earn money online and offline with proven strategies, side hustles, and passive income ideas."

[advertisement]
image = "images/income-online.jpg"
link = "https://gethugothemes.com/"

[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post

[subscription]
enable = false
newsletter_title = "Newsletter"
newsletter_invitation = "Join thousands of Tiny Salt subscribers and get our best recipes delivered each week!"
newsletter_placeholder = "Type And Hit Enter"
newsletter_reminder_a = "By Singing Up, You Agree To"
newsletter_reminder_b = "Privacy Policy"
newsletter_button = "Sign in"

mailchimp_form_action = "https://gmail.us17.list-manage.com/subscribe/post?u=3392b2d612de88ac6644ca414&amp;id=3ecf0e3fef&amp;f_id=00e55de0f0" # replace this url with yours
mailchimp_form_name = "b_3392b2d612de88ac6644ca414_3ecf0e3fef" # replace this code with yours

[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://www.facebook.com/earnmoneynowonline"

[[social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/moneyonline_fre"

[[social]]
title = "instagram"
icon = "fab fa-instagram"
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/company/earn-money-online-free"